#Update all the sections by editing the data.yml file inside _data folder.

# Update all the sections by editing the data.yml file inside _data folder.

# Site Settings
title: Minjee Kim
url: "https://minjeekim.github.io"   # use HTTPS; change if using a custom domain
baseurl: ""                           # "" for user site; "/<repo-name>" for project site
description: "Bayesian Methods | Clinical Trials"
theme_skin: blue                      # blue turquoise green berry orange ceramic teal oceanstale
chrome_mobile_color:                  # e.g., "#1976d2" or leave empty

# Theme: use your repo’s layouts (Orbit fork), not GitHub’s default
theme: null

# Plugins allowed on GitHub Pages
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

# Tracker (remove UA; add GA4 only if your theme supports it)
# analytics: UA-83979019-1

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed

# Excludes (don’t publish these)
exclude:
  - README.md
  - node_modules
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - .github
  - scripts
  - vendor

# Build settings
compress-site: yes
encoding: "utf-8"
compress_html:
  clippings: all
  ignore:
    envs: development

# Development Settings
port: 4000
host: 0.0.0.0
safe: false
